# Generated by Django 3.1.dev20200317195702 on 2020-04-24 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100)),
                ('category_description', models.CharField(max_length=2500)),
            ],
            options={
                'db_table': 'home_categories',
                'ordering': ['category_name', 'category_description'],
            },
        ),
    ]
