# Generated by Django 3.1.dev20200317195702 on 2020-04-30 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('author', models.CharField(max_length=20)),
                ('image', models.FilePathField(path='/images')),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_name', models.CharField(max_length=100)),
                ('recipe_steps', models.CharField(max_length=2500)),
            ],
            options={
                'db_table': 'home_recipes',
                'ordering': ['recipe_name', 'recipe_steps'],
            },
        ),
    ]
