# Generated by Django 3.1.dev20200317195702 on 2020-04-24 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.CharField(max_length=2500)),
                ('recipe_name', models.CharField(max_length=100)),
                ('recipe_steps', models.CharField(max_length=2500)),
            ],
            options={
                'db_table': 'home_recipes',
                'ordering': ['category_id', 'recipe_name'],
            },
        ),
    ]
